# Generated by Django 2.2.4 on 2021-10-18 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='munhak_type',
        ),
        migrations.DeleteModel(
            name='MunhakType',
        ),
    ]
